-- Migration: Create tables for storing generation history and configure storage buckets for user uploads and generated images. This enables persistent history and image-to-image functionality with proper authentication.
-- Executed at: 2025-12-09T00:08:20Z
-- Generated by AI Agent

-- Create table for history
CREATE TABLE IF NOT EXISTS generated_images (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  image_url TEXT NOT NULL,
  prompt TEXT NOT NULL,
  style TEXT NOT NULL,
  seed BIGINT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE generated_images ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to ensure clean slate
DROP POLICY IF EXISTS "Users can view their own images" ON generated_images;
DROP POLICY IF EXISTS "Users can insert their own images" ON generated_images;

-- Policy for users to see their own images
CREATE POLICY "Users can view their own images" ON generated_images
  FOR SELECT USING (auth.uid() = user_id);

-- Policy for users to insert their own images
CREATE POLICY "Users can insert their own images" ON generated_images
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Storage bucket setup for user uploads (references)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('user_uploads', 'user_uploads', true)
ON CONFLICT (id) DO NOTHING;

-- Storage bucket setup for generated images (history)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('generated_images', 'generated_images', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing storage policies to avoid conflicts
DROP POLICY IF EXISTS "Public Access Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Uploads" ON storage.objects;
DROP POLICY IF EXISTS "Public View Generated" ON storage.objects;
DROP POLICY IF EXISTS "Auth Insert Generated" ON storage.objects;

-- Storage policies for user_uploads
CREATE POLICY "Public Access Uploads" ON storage.objects FOR SELECT USING (bucket_id = 'user_uploads');
CREATE POLICY "Authenticated Upload Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'user_uploads' AND auth.role() = 'authenticated');

-- Storage policies for generated_images
CREATE POLICY "Public View Generated" ON storage.objects FOR SELECT USING (bucket_id = 'generated_images');
CREATE POLICY "Auth Insert Generated" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'generated_images' AND auth.role() = 'authenticated');
