-- Migration: Create user_uploads storage bucket and set up public access policies to ensure image uploading works correctly for the Image-to-Image feature.
-- Executed at: 2025-12-09T00:05:48Z
-- Generated by AI Agent

-- Create the storage bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('user_uploads', 'user_uploads', true)
ON CONFLICT (id) DO NOTHING;

-- Remove existing policies to avoid conflicts and ensure clean state
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Allow public uploads" ON storage.objects;
DROP POLICY IF EXISTS "Allow public select" ON storage.objects;

-- Create a policy that allows anyone to upload files (for this demo app)
CREATE POLICY "Allow public uploads"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'user_uploads' );

-- Create a policy that allows anyone to view files
CREATE POLICY "Allow public select"
ON storage.objects FOR SELECT
USING ( bucket_id = 'user_uploads' );

-- Create a policy that allows anyone to update/delete their own files (optional but good)
-- For simplicity in this demo, we might just allow all or restrict. 
-- Let's keep it simple: Public Read/Write for this specific bucket for the demo.

